[package]
name = "minimal_proc_macro"
version = "0.1.0"
edition = "2024"


[lib]
proc-macro = true

[dependencies]
naga = {version="23.1.0", features=["wgsl-in"]}
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = { version = "2.0.94", features = ["full"]   }
