name: Cargo Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: ['bevy_gpu_compute_macro', 'bevy_gpu_compute_core', 'bevy_gpu_compute'] 
    steps:
    - uses: actions/checkout@v4
    - name: Build for ${{ matrix.crate }}
      run: |
        rustup update nightly && rustup default nightly
        cargo build --verbose
        cargo test --verbose
      working-directory: ./${{ matrix.crate }}
