name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: ['bevy_gpu_compute_macro', 'bevy_gpu_compute_core', 'bevy_gpu_compute'] 
    steps:
    - uses: actions/checkout@v4
    - name: Build for ${{ matrix.crate }}
      run: cargo build --verbose
      working-directory: ./${{ matrix.crate }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: ['bevy_gpu_compute_macro', 'bevy_gpu_compute_core', 'bevy_gpu_compute']  # Replace with your actual crate directory names
    steps:
    - uses: actions/checkout@v4
    - name: Run tests for ${{ matrix.crate }}
      run: cargo test --verbose
      working-directory: ./${{ matrix.crate }}
